import React from 'react';
import './workexperiences.css';


const WorkExperiences = () => {
  return (
    <section className="work-experiences">
      <h2 className='PageTitle' id='Introduction'>
        Work Experiences
      </h2>
      <div className="experience1">
        <div className="image-container">
          <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Rivian_logo_and_wordmark.svg/2560px-Rivian_logo_and_wordmark.svg.png' alt='Rivian Logo' id='experience-img'></img>
        </div>
        <div className="position-title">
        <span class="text-star"> ✦ </span> 
        Rotational (Trail) Engineer
        <span class="text-star"> ✦ </span>
          </div>
        <div className="month-date">July 2022 - Feb 2023</div>
        <div className='body'>
          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>EPA Certification Support
            <span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                I contributed significantly by ensuring compliance with EPA certification testing and analysis standards and regulations.
                This compliance was crucial for the successful launch of multiple car programs, as it helped meet environmental requirements
                and gain necessary certifications.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>Simulated Range Forecasts:
            <span class="text-spike">✹ </span>
            </div>
            <div className="body-content">
              <p>
                I effectively utilized AMSIMs software to deliver accurate and comprehensive simulated range forecasts.
                These forecasts played a pivotal role in supporting data-driven decision-making processes and enabling
                program-level changes for current and future programs.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>Influential Data
            <span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                The numbers generated through my work had a substantial impact on high-stake decisions made by key stakeholders regarding
                future programs. This data not only provided valuable insights but also shaped the direction of critical projects.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>
            Cross-Team Collaboration:
            <span class="text-spike">✹ </span>
            </div>
            <div className="body-content">
              <p>
                My role fostered cross-collaboration with numerous other teams within the organization.
                This collaborative approach was essential for coordinating efforts, sharing insights,
                and ensuring the success of our programs.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="experience2">
        <div className="position-title">
        <span class="text-star"> ✦ </span>
          Range & Efficiency Engineering Intern
          <span class="text-star"> ✦ </span>
          </div>
        <div className="month-date">June 2021 - August 2021</div>
        <div className="experienceSection2">
          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>
            Sub-Vehicle Model Development:
            <span class="text-spike">✹ </span>
            </div>
            <div className="body-contentSub">
              <p>
                I took the initiative to develop a sub-vehicle model using MATLAB/Simulink. This model was designed to simulate road load forces, a critical aspect in vehicle performance analysis.
              </p>
            </div>
          </div>
          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>Validation and Analysis<span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                To ensure the accuracy and reliability of the model, I conducted thorough validation and analysis. This involved comparing the simulated results generated by the model with real-world coast-down test data. This validation process played a crucial role in confirming the model's effectiveness and precision.
              </p>
            </div>
          </div>
          <div className="experienceSection">
            <div className="subtitle">
            <span class="text-spike">✹ </span>
            Integrated Propulsion System
            <span class="text-spike">✹ </span>
            </div>
            <div className="body-content">
              <p>
                I successfully integrated this sub-vehicle model with an existing propulsion system within Simulink. This integration was a significant achievement, as it allowed for a more comprehensive analysis of the vehicle's behavior under different conditions.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="experience3">
      <div className="image-container">
          <h1 id='MCFL'>Multiphase and Complex Fluid Lab 
          <br/>
            at California State University, Long Beach
            </h1>
        </div>
        <div className="position-title">
        <span class="text-star"> ✦ </span>
        Undergraduate Research Assistant
        <span class="text-star"> ✦ </span></div>
        <div className="month-date">August 2021 - May 2022</div>
        <div className="background">
          <div className="background-top">Background</div>
              <p id='background-p'>
              My research delved into fluid dynamics in zero-gravity environments, where traditional experiments are often expensive and logistically challenging. 
              To overcome these obstacles, we employed Computational Fluid Dynamics (CFD) simulations. These simulations allowed us to study fluid behavior in zero gravity 
              without the need for costly physical experiments.  
              One crucial aspect we considered was the influence of Earth's gravity on fluid dynamics. 
              On Earth, gravity significantly affects how fluids move. In our simulations, we incorporated equations to account 
              for this influence. This research enhanced our understanding of fluid behavior in zero gravity and has applications 
              in aerospace and space exploration.
              </p>
            </div>
            <div className='experienceContainer'>
            <div className="experienceSection" id='background'>
            <div className="subtitle">
            <span class="text-spike">✹</span>Variable Gathering<span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                Meticulously gathered and documented relevant variables, including fluid characteristics such as viscosity and density, ensuring the accuracy and reliability of simulations to closely mimic real-world conditions and gravitational effects.
              </p>
            </div>
          </div>
          <div className="experienceSection" id='background'>
            <div className="subtitle"><span class="text-spike">✹ </span>Governing Equations<span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
              Navier-Stokes and Energy Equations for liquid and vapor phase:
              </p>
              <div className="image-container">
              {/* <img src={NSEqn} alt='Navier-Stokes Equations' id='NSEqn'></img> */}
              <div className='equations'>
              ∂𝜌/∂𝑡 + ∇(𝜌𝐯) = 0 <span class="check">✓</span><br/>
                ∂/∂𝑡(𝜌𝐯) + ∇(𝜌𝐯𝐯) = -∇𝑝 + ∇ [𝜇𝑒𝑓𝑓(∇𝐯 + ∇ν𝑇)] + 𝜌𝐠 + 𝐅𝑣𝑜𝑙 <span class="check">✓</span> <br/>
                ∂/∂𝑡(𝜌𝐸) + ∇(𝐯(𝜌𝐸 + 𝑝)) = ∇(𝑘𝑒𝑓𝑓∇𝑇) + 𝑆ℎ; <span class="check">✓</span>
              </div>
              <p>
              Ready more about the case-study {""}
              <span className="center-link">
                <a
                  href="https://ntrs.nasa.gov/api/citations/20190030757/downloads/20190030757.pdf"
                  className="link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  HERE
                </a>
              </span>
            </p>
              </div>
            </div>
            </div>
            </div>
            <div className='experienceContainer'>
          <div className="experienceSection">
            <div className="subtitle"><span class="text-spike">✹ </span>Gravitational Influences<span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                Developed and incorporated equations to account for the influence of Earth's gravity on fluid dynamics, enhancing understanding of fluid behavior in zero gravity, with potential applications in aerospace and space exploration.
              </p>
            </div>
          </div>
          <div className="experienceSection">
            <div className="subtitle"><span class="text-spike">✹ </span>CAD Model Development:<span class="text-spike">✹ </span></div>
            <div className="body-content">
              <p>
                Created a precise CAD model using SolidWorks, accurately representing the experimental setup for effective simulation and analysis of fluid behavior in zero-gravity conditions.
              </p>
            </div>
          </div>
          </div>
      </div>
</section>
);
};

export default WorkExperiences;

