import React from 'react';
import './workexperiences.css';
import header from '../../images/workexperienceHeader.png';
import Rivian from '../../images/Rivian.png';
import MCFFL from '../../images/MCFFL.png'
import NSEqn from '../../images/NSEqn.png'

const WorkExperiences = () => {
  return (
    <section className="work-experiences">
      <div className="workexperienceHeader">
        <img src={header} alt="Work Experience Header" />
      </div>
      <div className="experience1">
        <div className="image-container">
          <img src={Rivian} alt='Rivian Logo' id='experience-img'></img>
        </div>
        <div className="position-title">Rotational (Trail) Engineer</div>
        <div className="month-date">July 2022 - Feb 2023</div>
        <div className='body'>
          <div className="experienceSection">
            <div className="subtitle">EPA Certification Support:</div>
            <div className="body-content">
              <p>
                I contributed significantly by ensuring compliance with EPA certification testing and analysis standards and regulations.
                This compliance was crucial for the successful launch of multiple car programs, as it helped meet environmental requirements
                and gain necessary certifications.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">Simulated Range Forecasts:</div>
            <div className="body-content">
              <p>
                I effectively utilized AMSIMs software to deliver accurate and comprehensive simulated range forecasts.
                These forecasts played a pivotal role in supporting data-driven decision-making processes and enabling
                program-level changes for current and future programs.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">Influential Data:</div>
            <div className="body-content">
              <p>
                The numbers generated through my work had a substantial impact on high-stake decisions made by key stakeholders regarding
                future programs. This data not only provided valuable insights but also shaped the direction of critical projects.
              </p>
            </div>
          </div>

          <div className="experienceSection">
            <div className="subtitle">Cross-Team Collaboration:</div>
            <div className="body-content">
              <p>
                My role fostered cross-collaboration with numerous other teams within the organization.
                This collaborative approach was essential for coordinating efforts, sharing insights,
                and ensuring the success of our programs.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="experience2">
        <div className="position-title">Range & Efficiency Engineering Intern</div>
        <div className="month-date">June 2021 - August 2021</div>
        <div className="experienceSection2">
          <div className="experienceSection">
            <div className="subtitle">Sub-Vehicle Model Development:</div>
            <div className="body-content">
              <p>
                I took the initiative to develop a sub-vehicle model using MATLAB/Simulink. This model was designed to simulate road load forces, a critical aspect in vehicle performance analysis.
              </p>
            </div>
          </div>
          <div className="experienceSection">
            <div className="subtitle">Validation and Analysis:</div>
            <div className="body-content">
              <p>
                To ensure the accuracy and reliability of the model, I conducted thorough validation and analysis. This involved comparing the simulated results generated by the model with real-world coast-down test data. This validation process played a crucial role in confirming the model's effectiveness and precision.
              </p>
            </div>
          </div>
          <div className="experienceSection">
            <div className="subtitle">Integration with Propulsion System:</div>
            <div className="body-content">
              <p>
                I successfully integrated this sub-vehicle model with an existing propulsion system within Simulink. This integration was a significant achievement, as it allowed for a more comprehensive analysis of the vehicle's behavior under different conditions.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="experience3">
      <div className="image-container">
          <img src={MCFFL} alt='MCFFL Logo' id='experience-img'></img>
        </div>
        <div className="position-title">Undergraduate Research Assistant</div>
        <div className="month-date">August 2021 - May 2022</div>
      <div className="experienceSection">
        <div className="subtitle">Incorporating Gravitational Influences:</div>
        <div className="body-content">
          <p>
            Developed and incorporated equations to account for the influence of Earth's gravity on fluid dynamics, enhancing understanding of fluid behavior in zero gravity, with potential applications in aerospace and space exploration.
          </p>
        </div>
      </div>
      <div className="experienceSection">
        <div className="subtitle">CAD Model Development:</div>
        <div className="body-content">
          <p>
            Created a precise CAD model using SolidWorks, accurately representing the experimental setup for effective simulation and analysis of fluid behavior in zero-gravity conditions.
          </p>
        </div>
      </div>
      <div className="experienceSection">
        <div className="subtitle">Variable Gathering and Documentation:</div>
        <div className="body-content">
          <p>
            Meticulously gathered and documented relevant variables, including fluid characteristics such as viscosity and density, ensuring the accuracy and reliability of simulations to closely mimic real-world conditions and gravitational effects.
          </p>
        </div>
      </div>
      <div className="experienceSection">
        <div className="subtitle">Governing Equations:</div>
        <div className="body-content">
          <p>
          Navier-Stokes and Energy Equation for liquid and vapor phase
          </p>
          <div className="image-container">
          <img src={NSEqn} alt='Navier-Stokes Equations' id='NSEqn'></img>
          <p>
          Ready more about the case-study
          </p>
          <a href="https://ntrs.nasa.gov/api/citations/20190030757/downloads/20190030757.pdf" className="subtitle" target="_blank" rel="noopener noreferrer">HERE</a>
        </div>
        </div>
      </div>
    </div>
</section>
);
};

export default WorkExperiences;

